import { cloneData } from "@/lib/utils/format";

export const products = [
  {
    id: "prod-croissant",
    code: "PRD-001",
    name: "Butter Croissant",
    category: "Pastry",
    sellingPrice: 18500,
    unit: "pcs",
    shelfLife: 2,
    status: "Aktif",
    finishedStock: 280,
  },
  {
    id: "prod-danish",
    code: "PRD-002",
    name: "Chocolate Danish",
    category: "Pastry",
    sellingPrice: 20000,
    unit: "pcs",
    shelfLife: 2,
    status: "Aktif",
    finishedStock: 210,
  },
  {
    id: "prod-cheese-bun",
    code: "PRD-003",
    name: "Cheese Bun Premium",
    category: "Roti Manis",
    sellingPrice: 16000,
    unit: "pcs",
    shelfLife: 3,
    status: "Aktif",
    finishedStock: 340,
  },
  {
    id: "prod-cinnamon-roll",
    code: "PRD-004",
    name: "Cinnamon Roll",
    category: "Roti Manis",
    sellingPrice: 17500,
    unit: "pcs",
    shelfLife: 3,
    status: "Aktif",
    finishedStock: 190,
  },
  {
    id: "prod-garlic-cream",
    code: "PRD-005",
    name: "Garlic Cream Bread",
    category: "Savory Bread",
    sellingPrice: 15500,
    unit: "pcs",
    shelfLife: 2,
    status: "Aktif",
    finishedStock: 260,
  },
];

export const rawMaterials = [
  {
    id: "raw-flour",
    code: "BB-001",
    name: "Tepung Terigu Premium",
    category: "Tepung",
    inventoryUnit: "kg",
    currentStock: 132,
    safetyStock: 150,
    minimumStock: 120,
    warehouseLocation: "Rak A1",
    status: "Aktif",
  },
  {
    id: "raw-butter",
    code: "BB-002",
    name: "Butter",
    category: "Dairy",
    inventoryUnit: "kg",
    currentStock: 95,
    safetyStock: 70,
    minimumStock: 50,
    warehouseLocation: "Cold Room B1",
    status: "Aktif",
  },
  {
    id: "raw-sugar",
    code: "BB-003",
    name: "Gula Pasir",
    category: "Pemanis",
    inventoryUnit: "kg",
    currentStock: 78,
    safetyStock: 80,
    minimumStock: 55,
    warehouseLocation: "Rak A3",
    status: "Aktif",
  },
  {
    id: "raw-egg",
    code: "BB-004",
    name: "Telur Ayam",
    category: "Protein",
    inventoryUnit: "butir",
    currentStock: 760,
    safetyStock: 600,
    minimumStock: 450,
    warehouseLocation: "Cold Room B2",
    status: "Aktif",
  },
  {
    id: "raw-milk",
    code: "BB-005",
    name: "Susu Cair",
    category: "Dairy",
    inventoryUnit: "liter",
    currentStock: 92,
    safetyStock: 85,
    minimumStock: 65,
    warehouseLocation: "Cold Room B1",
    status: "Aktif",
  },
  {
    id: "raw-yeast",
    code: "BB-006",
    name: "Ragi Instan",
    category: "Pengembang",
    inventoryUnit: "kg",
    currentStock: 18,
    safetyStock: 20,
    minimumStock: 12,
    warehouseLocation: "Rak A2",
    status: "Aktif",
  },
  {
    id: "raw-mozzarella",
    code: "BB-007",
    name: "Keju Mozzarella",
    category: "Dairy",
    inventoryUnit: "kg",
    currentStock: 64,
    safetyStock: 45,
    minimumStock: 35,
    warehouseLocation: "Cold Room B3",
    status: "Aktif",
  },
  {
    id: "raw-cinnamon",
    code: "BB-008",
    name: "Bubuk Kayu Manis",
    category: "Rempah",
    inventoryUnit: "kg",
    currentStock: 8,
    safetyStock: 10,
    minimumStock: 6,
    warehouseLocation: "Rak C1",
    status: "Aktif",
  },
  {
    id: "raw-garlic",
    code: "BB-009",
    name: "Bawang Putih",
    category: "Rempah",
    inventoryUnit: "kg",
    currentStock: 22,
    safetyStock: 18,
    minimumStock: 12,
    warehouseLocation: "Rak C2",
    status: "Aktif",
  },
  {
    id: "raw-chocolate",
    code: "BB-010",
    name: "Coklat Compound",
    category: "Coklat",
    inventoryUnit: "kg",
    currentStock: 42,
    safetyStock: 45,
    minimumStock: 30,
    warehouseLocation: "Rak C3",
    status: "Aktif",
  },
];

function bomItem(productId, rawMaterialId, quantityPerProduct, usageUnit, inventoryUnit, conversionFactor) {
  return {
    id: `bom-${productId}-${rawMaterialId}`,
    productId,
    rawMaterialId,
    quantityPerProduct,
    usageUnit,
    inventoryUnit,
    conversionFactor,
  };
}

export const bom = [
  bomItem("prod-croissant", "raw-flour", 80, "gram", "kg", 0.001),
  bomItem("prod-croissant", "raw-butter", 35, "gram", "kg", 0.001),
  bomItem("prod-croissant", "raw-sugar", 8, "gram", "kg", 0.001),
  bomItem("prod-croissant", "raw-egg", 0.15, "butir", "butir", 1),
  bomItem("prod-croissant", "raw-milk", 35, "mililiter", "liter", 0.001),
  bomItem("prod-croissant", "raw-yeast", 2, "gram", "kg", 0.001),

  bomItem("prod-danish", "raw-flour", 75, "gram", "kg", 0.001),
  bomItem("prod-danish", "raw-butter", 28, "gram", "kg", 0.001),
  bomItem("prod-danish", "raw-sugar", 12, "gram", "kg", 0.001),
  bomItem("prod-danish", "raw-egg", 0.12, "butir", "butir", 1),
  bomItem("prod-danish", "raw-milk", 30, "mililiter", "liter", 0.001),
  bomItem("prod-danish", "raw-yeast", 2, "gram", "kg", 0.001),
  bomItem("prod-danish", "raw-chocolate", 25, "gram", "kg", 0.001),

  bomItem("prod-cheese-bun", "raw-flour", 70, "gram", "kg", 0.001),
  bomItem("prod-cheese-bun", "raw-butter", 15, "gram", "kg", 0.001),
  bomItem("prod-cheese-bun", "raw-sugar", 8, "gram", "kg", 0.001),
  bomItem("prod-cheese-bun", "raw-egg", 0.1, "butir", "butir", 1),
  bomItem("prod-cheese-bun", "raw-milk", 28, "mililiter", "liter", 0.001),
  bomItem("prod-cheese-bun", "raw-yeast", 2, "gram", "kg", 0.001),
  bomItem("prod-cheese-bun", "raw-mozzarella", 22, "gram", "kg", 0.001),

  bomItem("prod-cinnamon-roll", "raw-flour", 85, "gram", "kg", 0.001),
  bomItem("prod-cinnamon-roll", "raw-butter", 20, "gram", "kg", 0.001),
  bomItem("prod-cinnamon-roll", "raw-sugar", 16, "gram", "kg", 0.001),
  bomItem("prod-cinnamon-roll", "raw-egg", 0.12, "butir", "butir", 1),
  bomItem("prod-cinnamon-roll", "raw-milk", 35, "mililiter", "liter", 0.001),
  bomItem("prod-cinnamon-roll", "raw-yeast", 2, "gram", "kg", 0.001),
  bomItem("prod-cinnamon-roll", "raw-cinnamon", 3, "gram", "kg", 0.001),

  bomItem("prod-garlic-cream", "raw-flour", 78, "gram", "kg", 0.001),
  bomItem("prod-garlic-cream", "raw-butter", 18, "gram", "kg", 0.001),
  bomItem("prod-garlic-cream", "raw-sugar", 5, "gram", "kg", 0.001),
  bomItem("prod-garlic-cream", "raw-egg", 0.1, "butir", "butir", 1),
  bomItem("prod-garlic-cream", "raw-milk", 25, "mililiter", "liter", 0.001),
  bomItem("prod-garlic-cream", "raw-yeast", 2, "gram", "kg", 0.001),
  bomItem("prod-garlic-cream", "raw-garlic", 4, "gram", "kg", 0.001),
  bomItem("prod-garlic-cream", "raw-mozzarella", 15, "gram", "kg", 0.001),
];

const supplierNames = [
  "PT Gandum Nusantara",
  "CV Sari Tepung Jaya",
  "UD Pangan Prima",
  "PT Dairy Fresh Indonesia",
  "CV Butter Makmur",
  "Koperasi Susu Lembang",
  "PT Gula Sentosa",
  "CV Manis Sejahtera",
  "UD Sumber Rasa",
  "Peternakan Telur Barokah",
  "CV Unggas Mandiri",
  "PT Protein Pagi",
  "PT Susu Murni Jabar",
  "CV Dairy Lokal",
  "UD Segar Harian",
  "PT Fermenta Bakery",
  "CV Ragi Kencana",
  "UD Bahan Roti Cepat",
  "PT Keju Prima",
  "CV Mozza Lestari",
  "UD Dairy Artisan",
  "PT Rempah Aromatik",
  "CV Kayu Manis Timur",
  "UD Rempah Wangi",
  "PT Bumbu Dapur Jaya",
  "CV Garlic Fresh",
  "UD Bawang Nusantara",
  "PT Coklat Rasa",
  "CV Cocoa Sentosa",
  "UD Coklat Mandiri",
];

export const suppliers = supplierNames.map((name, index) => ({
  id: `sup-${String(index + 1).padStart(2, "0")}`,
  code: `SUP-${String(index + 1).padStart(3, "0")}`,
  name,
  address: `Jl. Industri Bakery No. ${index + 11}, Bandung`,
  contact: ["Budi Santoso", "Siti Rahma", "Agus Pratama", "Dewi Lestari", "Rina Maharani"][
    index % 5
  ],
  phone: `08${String(1200000000 + index * 7321).slice(0, 10)}`,
  email: `supplier${index + 1}@contoh.id`,
  distance: [8, 12, 18, 24, 32, 15, 27, 36, 42, 55][index % 10],
  status: index % 9 === 0 ? "Evaluasi" : "Aktif",
}));

const offerTemplates = [
  ["raw-flour", "kg", 13000, 4.6, 540, 8, 50, 2],
  ["raw-flour", "kg", 12600, 4.3, 430, 12, 40, 3],
  ["raw-flour", "kg", 12100, 4.1, 360, 18, 35, 4],
  ["raw-butter", "kg", 92000, 4.8, 250, 24, 20, 4],
  ["raw-butter", "kg", 89000, 4.4, 220, 32, 18, 5],
  ["raw-butter", "kg", 94000, 4.7, 180, 15, 15, 3],
  ["raw-sugar", "kg", 15600, 4.4, 360, 27, 30, 3],
  ["raw-sugar", "kg", 14900, 4.1, 320, 36, 25, 4],
  ["raw-sugar", "kg", 15100, 4.3, 280, 42, 20, 5],
  ["raw-egg", "butir", 2200, 4.5, 2300, 55, 300, 2],
  ["raw-egg", "butir", 2150, 4.2, 1900, 21, 250, 2],
  ["raw-egg", "butir", 2300, 4.7, 1600, 33, 200, 1],
  ["raw-milk", "liter", 18500, 4.6, 320, 14, 25, 2],
  ["raw-milk", "liter", 17900, 4.3, 280, 22, 20, 3],
  ["raw-milk", "liter", 18800, 4.7, 220, 18, 18, 2],
  ["raw-yeast", "kg", 69000, 4.5, 80, 26, 5, 3],
  ["raw-yeast", "kg", 66000, 4.2, 70, 31, 5, 4],
  ["raw-yeast", "kg", 71000, 4.7, 60, 19, 4, 2],
  ["raw-mozzarella", "kg", 76000, 4.6, 180, 28, 15, 4],
  ["raw-mozzarella", "kg", 73000, 4.3, 150, 35, 12, 5],
  ["raw-mozzarella", "kg", 79000, 4.8, 120, 23, 10, 3],
  ["raw-cinnamon", "kg", 118000, 4.4, 45, 38, 3, 5],
  ["raw-cinnamon", "kg", 113000, 4.1, 38, 44, 2, 6],
  ["raw-cinnamon", "kg", 121000, 4.6, 32, 29, 2, 4],
  ["raw-garlic", "kg", 34000, 4.3, 100, 16, 8, 2],
  ["raw-garlic", "kg", 32000, 4.1, 86, 24, 6, 3],
  ["raw-garlic", "kg", 36000, 4.5, 74, 31, 5, 2],
  ["raw-chocolate", "kg", 61000, 4.6, 160, 26, 12, 4],
  ["raw-chocolate", "kg", 58500, 4.3, 145, 34, 10, 5],
  ["raw-chocolate", "kg", 63000, 4.8, 120, 22, 8, 3],
];

export const supplierOffers = offerTemplates.map((template, index) => {
  const [rawMaterialId, unit, price, qualityScore, capacity, distance, minimumOrder, leadTime] = template;
  const supplierId = `sup-${String(index + 1).padStart(2, "0")}`;

  return {
    id: `offer-${String(index + 1).padStart(2, "0")}`,
    supplierId,
    rawMaterialId,
    price,
    qualityScore,
    capacity,
    distance,
    minimumOrder,
    leadTime,
    unit,
  };
});

export const customers = [
  {
    id: "cust-01",
    code: "CUST-001",
    name: "Daily Mart Dago",
    type: "Retail",
    region: "Bandung Utara",
    contact: "Maya",
    phone: "0812345001",
    address: "Jl. Dago No. 88, Bandung",
    status: "Aktif",
  },
  {
    id: "cust-02",
    code: "CUST-002",
    name: "Kafe Sudut Kota",
    type: "HoReCa",
    region: "Bandung Tengah",
    contact: "Rizki",
    phone: "0812345002",
    address: "Jl. Braga No. 21, Bandung",
    status: "Aktif",
  },
  {
    id: "cust-03",
    code: "CUST-003",
    name: "Morning Bite Distributor",
    type: "Distributor",
    region: "Cimahi",
    contact: "Nadia",
    phone: "0812345003",
    address: "Jl. Amir Machmud No. 41, Cimahi",
    status: "Aktif",
  },
  {
    id: "cust-04",
    code: "CUST-004",
    name: "Hotel Lembah Sari",
    type: "HoReCa",
    region: "Lembang",
    contact: "Teguh",
    phone: "0812345004",
    address: "Jl. Raya Lembang No. 15, Lembang",
    status: "Aktif",
  },
  {
    id: "cust-05",
    code: "CUST-005",
    name: "Fresh Corner Setiabudi",
    type: "Retail",
    region: "Bandung Utara",
    contact: "Anisa",
    phone: "0812345005",
    address: "Jl. Setiabudi No. 109, Bandung",
    status: "Aktif",
  },
  {
    id: "cust-06",
    code: "CUST-006",
    name: "Roti Pagi Agency",
    type: "Distributor",
    region: "Bandung Timur",
    contact: "Dimas",
    phone: "0812345006",
    address: "Jl. Soekarno Hatta No. 250, Bandung",
    status: "Aktif",
  },
];

const periods = [
  "2025-07",
  "2025-08",
  "2025-09",
  "2025-10",
  "2025-11",
  "2025-12",
  "2026-01",
  "2026-02",
  "2026-03",
  "2026-04",
  "2026-05",
  "2026-06",
];

const salesSeries = {
  "prod-croissant": [1180, 1215, 1206, 1264, 1298, 1355, 1332, 1386, 1410, 1458, 1436, 1504],
  "prod-danish": [910, 945, 938, 972, 1010, 1044, 1028, 1065, 1098, 1125, 1110, 1168],
  "prod-cheese-bun": [760, 794, 812, 805, 850, 878, 902, 895, 936, 952, 980, 1008],
  "prod-cinnamon-roll": [640, 655, 682, 674, 718, 742, 730, 768, 791, 784, 828, 856],
  "prod-garlic-cream": [830, 858, 846, 889, 912, 948, 935, 975, 1002, 992, 1036, 1075],
};

export const monthlySales = Object.entries(salesSeries).flatMap(([productId, values]) =>
  values.map((quantity, index) => ({
    id: `sale-${productId}-${periods[index]}`,
    productId,
    period: periods[index],
    quantity,
    channel: index % 3 === 0 ? "Retail" : index % 3 === 1 ? "Distributor" : "HoReCa",
  }))
);

export const forecasts = [
  {
    id: "forecast-001",
    productId: "prod-croissant",
    period: "2026-07",
    historicalPeriods: 12,
    quantity: 1524,
    predictedQuantity: 1524,
    method: "Regresi Linier",
    status: "Disetujui",
    createdAt: "2026-07-01",
    calculation: null,
  },
  {
    id: "forecast-002",
    productId: "prod-danish",
    period: "2026-07",
    historicalPeriods: 12,
    quantity: 1184,
    predictedQuantity: 1184,
    method: "Regresi Linier",
    status: "Disetujui",
    createdAt: "2026-07-01",
    calculation: null,
  },
];

export const materialRequirements = [
  {
    id: "mr-raw-flour-2026-07",
    period: "2026-07",
    rawMaterialId: "raw-flour",
    rawMaterialName: "Tepung Terigu Premium",
    inventoryUnit: "kg",
    totalGrossRequirement: 210.72,
    products: [],
    status: "Dihitung",
  },
  {
    id: "mr-raw-butter-2026-07",
    period: "2026-07",
    rawMaterialId: "raw-butter",
    rawMaterialName: "Butter",
    inventoryUnit: "kg",
    totalGrossRequirement: 86.54,
    products: [],
    status: "Dihitung",
  },
  {
    id: "mr-raw-milk-2026-07",
    period: "2026-07",
    rawMaterialId: "raw-milk",
    rawMaterialName: "Susu Cair",
    inventoryUnit: "liter",
    totalGrossRequirement: 88.86,
    products: [],
    status: "Dihitung",
  },
];

export const inventories = [
  ...rawMaterials.map((material) => ({
    id: `inv-${material.id}`,
    itemType: "raw-material",
    rawMaterialId: material.id,
    productId: "",
    currentStock: material.currentStock,
    safetyStock: material.safetyStock,
    minimumStock: material.minimumStock,
    inventoryUnit: material.inventoryUnit,
    warehouseLocation: material.warehouseLocation,
  })),
  ...products.map((product) => ({
    id: `inv-${product.id}`,
    itemType: "finished-product",
    rawMaterialId: "",
    productId: product.id,
    currentStock: product.finishedStock,
    safetyStock: 120,
    minimumStock: 80,
    inventoryUnit: "pcs",
    warehouseLocation: "Gudang Produk Jadi",
  })),
];

export const inventoryMovements = [
  {
    id: "mov-001",
    date: "2026-06-28",
    itemType: "raw-material",
    itemId: "raw-flour",
    type: "Masuk",
    quantity: 120,
    unit: "kg",
    reference: "PO-2026-0004",
    notes: "Penerimaan tepung batch akhir Juni.",
  },
  {
    id: "mov-002",
    date: "2026-06-30",
    itemType: "raw-material",
    itemId: "raw-butter",
    type: "Keluar",
    quantity: 42,
    unit: "kg",
    reference: "PROD-2026-0012",
    notes: "Pemakaian produksi pastry.",
  },
  {
    id: "mov-003",
    date: "2026-07-01",
    itemType: "finished-product",
    itemId: "prod-croissant",
    type: "Masuk",
    quantity: 180,
    unit: "pcs",
    reference: "PROD-2026-0013",
    notes: "Hasil produksi pagi.",
  },
];

export const procurementPlans = [
  {
    id: "plan-001",
    period: "2026-07",
    rawMaterialId: "raw-flour",
    rawMaterialName: "Tepung Terigu Premium",
    grossRequirement: 210.72,
    currentStock: 132,
    safetyStock: 150,
    netRequirement: 228.72,
    selectedSupplierId: "sup-01",
    selectedOfferId: "offer-01",
    selectedSupplierName: "PT Gandum Nusantara",
    minimumOrder: 50,
    finalOrderQuantity: 228.72,
    unitPrice: 13000,
    inventoryUnit: "kg",
    status: "Direncanakan",
  },
  {
    id: "plan-002",
    period: "2026-07",
    rawMaterialId: "raw-sugar",
    rawMaterialName: "Gula Pasir",
    grossRequirement: 26.39,
    currentStock: 78,
    safetyStock: 80,
    netRequirement: 28.39,
    selectedSupplierId: "sup-07",
    selectedOfferId: "offer-07",
    selectedSupplierName: "PT Gula Sentosa",
    minimumOrder: 30,
    finalOrderQuantity: 30,
    unitPrice: 15600,
    inventoryUnit: "kg",
    status: "Direncanakan",
  },
];

export const purchaseOrders = [
  {
    id: "po-001",
    number: "PO-2026-0001",
    supplierId: "sup-01",
    supplierName: "PT Gandum Nusantara",
    orderDate: "2026-07-01",
    expectedArrivalDate: "2026-07-03",
    status: "Diajukan",
    items: [
      {
        id: "poitem-001",
        rawMaterialId: "raw-flour",
        rawMaterialName: "Tepung Terigu Premium",
        quantity: 228.72,
        unit: "kg",
        unitPrice: 13000,
      },
    ],
    notes: "Simulasi PO dari rencana pengadaan tepung.",
  },
];

export const receivingRecords = [
  {
    id: "recv-001",
    purchaseOrderId: "po-001",
    poNumber: "PO-2026-0001",
    deliveryOrderNumber: "DO-GND-0701",
    receivedDate: "2026-07-02",
    rawMaterialId: "raw-flour",
    orderedQuantity: 228.72,
    receivedQuantity: 100,
    rejectedQuantity: 0,
    unit: "kg",
    qualityResult: "Baik",
    notes: "Penerimaan sebagian untuk simulasi.",
    status: "Dikonfirmasi",
  },
];

export const productionOrders = [
  {
    id: "prod-order-001",
    number: "PROD-2026-001",
    productId: "prod-croissant",
    forecastId: "forecast-001",
    targetQuantity: 500,
    scheduledDate: "2026-07-04",
    status: "Direncanakan",
    actualGoodQuantity: 0,
    failedQuantity: 0,
    notes: "Produksi croissant untuk permintaan awal Juli.",
  },
];

export const distributions = [
  {
    id: "dist-001",
    deliveryNoteNumber: "SJ-2026-0001",
    customerId: "cust-01",
    productId: "prod-croissant",
    quantity: 120,
    shipmentDate: "2026-07-04",
    vehicle: "Mobil Box B 1024 SCM",
    status: "Dijadwalkan",
    recipientName: "Maya",
    recipientPhone: "0812345001",
    notes: "Pengiriman pagi ke Daily Mart Dago.",
  },
];

export const notifications = [
  {
    id: "notif-001",
    title: "Stok Tepung Menipis",
    message: "Tepung Terigu Premium berada di bawah safety stock.",
    createdAt: "2026-07-02T08:00:00.000Z",
    read: false,
  },
  {
    id: "notif-002",
    title: "PO Menunggu Persetujuan",
    message: "PO-2026-0001 perlu ditinjau oleh Purchasing.",
    createdAt: "2026-07-02T09:30:00.000Z",
    read: false,
  },
];

export const defaultScmData = {
  products,
  rawMaterials,
  bom,
  suppliers,
  supplierOffers,
  customers,
  monthlySales,
  forecasts,
  materialRequirements,
  inventories,
  inventoryMovements,
  procurementPlans,
  purchaseOrders,
  receivingRecords,
  productionOrders,
  distributions,
  notifications,
};

export function getDefaultScmData() {
  return cloneData(defaultScmData);
}
